[theme]
base = "light"
primaryColor = "#0D352D"
backgroundColor = "#FAFBF7"
secondaryBackgroundColor = "#E9F0E7"
textColor = "#14231D"
font = "sans-serif"

[server]
maxUploadSize = 10
headless = true

[browser]
gatherUsageStats = false
